CURDIR := userland/lib/libc/src/stdio

OBJ-y := stdio.o vsprintf.o sprintf.o fopen.o fflush.o fclose.o \
		 iobcreate.o iobadd.o iobflush.o iobdestroy.o iobremove.o

LIBSUBDIRS-y :=

include $(SRCDIR)/mk/libsubdirs.mk
