CURDIR := userland/lib/libc/src/stdio

OBJ-y := stdio.o vsprintf.o sprintf.o fopen.o fflush.o fclose.o fread.o \
		 fputc.o putchar.o fputs.o puts.o vfprintf.o fprintf.o printf.o \
		 iobcreate.o iobadd.o iobflush.o iobdestroy.o iobremove.o iobread.o \
		 iobputc.o iobputi.o iobputu.o

LIBSUBDIRS-y :=

include $(SRCDIR)/mk/libsubdirs.mk
