CURDIR := userland/lib/libc/src/stdio

OBJ-y := stdio.o vsprintf.o sprintf.o fopen.o fflush.o fclose.o fread.o \
		 fputc.o \
		 iobcreate.o iobadd.o iobflush.o iobdestroy.o iobremove.o iobread.o \
		 iobputc.o

LIBSUBDIRS-y :=

include $(SRCDIR)/mk/libsubdirs.mk
