CURDIR := kernel/core/

OBJ := main.o string.o console.o kmalloc.o segment.o panic.o as.o region.o \
		interrupt.o timer.o cpu.o syscall.o module.o

BINSUBDIRS := proc/ scheduler/ vfs/ syscall/

include ${SRCDIR}mk/binsubdirs.mk
