CURDIR := kernel/core/

OBJ := main.o string.o console.o panic.o interrupt.o timer.o cpu.o syscall.o \
		module.o

BINSUBDIRS := mem/ proc/ scheduler/ vfs/ syscall/

include ${SRCDIR}mk/binsubdirs.mk
