CURDIR := kernel/core/fs/ops

OBJ-y := lookup.o mkdir.o mknod.o open.o read.o write.o lseek.o close.o \
	 stat.o ioctl.o dup.o getdirent.o open_device.o

BINSUBDIRS-y :=

include $(SRCDIR)/mk/binsubdirs.mk
