CURDIR := userland/lib/libc/src/string

OBJ-y := memcpy.o memset.o strlen.o strcpy.o strtok_r.o strcmp.o strncmp.o \
		 strcat.o memcmp.o strchr.o strrchr.o strdup.o

LIBSUBDIRS-y :=

include $(SRCDIR)/mk/libsubdirs.mk
