CURDIR := userland/driver/tty/

BIN := tty
INSTALL_DIR := bin
BINSUBDIRS := src/

tty_CFLAGS := $(USERLAND_CFLAGS)
tty_LDFLAGS := $(USERLAND_LDFLAGS)

tty_LIBS := libdriver libc

OBJ :=

include ${SRCDIR}mk/bin.mk
