CURDIR := userland/driver/video/

BIN := video
INSTALL_DIR := bin
BINSUBDIRS := src/

video_CFLAGS := $(USERLAND_CFLAGS)
video_LDFLAGS := $(USERLAND_LDFLAGS)

video_LIBS := libdriver libc

OBJ :=

include ${SRCDIR}mk/bin.mk
